### PR TITLE
More updates for new Codec Graph version

### PR DESCRIPTION
**Pull request by Core-i99**

### CODE REVIEW

**Comment by Core-i99** [comment]
@5T33Z0 
There are some more updates needed in [AppleALC_Layout-ID/README.md](https://github.com/5T33Z0/AppleALC-Guides/blob/main/AppleALC_Layout-ID/README.md), there is some text about the codec_dump_dec, I'll create a pr for it later.

**Comment by 5T33Z0** [comment]
It would be good, if the script would still genrate the dump_dec.txt since it is still needed.

**Comment by Core-i99** [comment]
What about including things like Amp Caps in each node and adding the CodecID inside the svg?
I'm don't know what's exactly all possible with Graphviz but it would be easier to have all information in a single file.

**Comment by 5T33Z0** [comment]
I agree. If that would be great. I should contain the CodecID and all the Nodes with `Control: name` since these are relevant for the routing options. Once you have something like this, I would test if it is useable and adjust the guide/workflow accordingly. It's been about halb a year or so since I wrote it, so I have to refresh my memory.

**Pull request merged**
